const prompt = {
  slug: "monsoon-forest-grade-prompt",

  title: "Monsoon Forest Grade Prompt",

  description:
    "Transform any image into a premium cinematic monsoon forest masterpiece with rich green tones, rainy atmosphere, soft mist, and natural color grading while preserving the main subject perfectly.",

  category: "Color Grading",

  image: "/images/prompts/monsoon-forest-grade-prompt.jpg",

  models: [
    "ChatGPT",
    "GPT Image",
    "Gemini",
    "Flux",
    "Midjourney",
    "Kling",
  ],

  prompt: `
Analyze the uploaded photograph and preserve the original subject, composition, perspective, lighting direction, identity, textures, and realism exactly as captured. Do not alter, replace, regenerate, reshape, or invent any objects, faces, backgrounds, or environmental elements.
Apply only a premium cinematic color grade inspired by lush monsoon forests and natural Kerala landscapes.
Create deep emerald and moss-green foliage with rich tonal depth while keeping greens natural and believable. Shift overly vibrant greens slightly toward olive and forest tones instead of neon. Preserve accurate skin tones and natural object colors.
Introduce soft warm highlights with subtle golden-yellow undertones while maintaining neutral whites. Keep shadows deep and clean with smooth transitions, avoiding crushed blacks.
Increase local contrast only around the subject to create gentle depth while keeping the background soft and atmospheric. Preserve realistic dynamic range with smooth highlight roll-off and rich shadow detail.
Reduce overall saturation slightly while allowing important colors to remain vibrant and naturally separated. Add subtle luminance to green areas instead of excessive saturation.
Apply soft cinematic contrast, refined micro-contrast, gentle texture enhancement, and moderate sharpening without halos or artificial clarity.
Maintain an authentic DSLR look with natural depth of field, creamy bokeh, realistic light falloff, and an organic photographic appearance.
Avoid HDR effects, excessive vibrance, oversharpening, orange skin, teal shadows, fake glow, exaggerated color shifts, AI-generated textures, plastic surfaces, or unrealistic enhancements.
The final image should feel calm, moody, timeless, realistic, and professionally color graded—as if edited by an experienced photographer rather than generated by AI.
Style Keywords
Cinematic
Moody
Forest Green
Moss Tones
Rich Blacks
Soft Contrast
Organic Greens
Natural Skin
DSLR Look
Premium Lightroom Edit
Realistic
Atmospheric
Kerala Monsoon Mood
Deep Bokeh
Editorial Photography
Timeless Color Science
`,
};

export default prompt;